# Generated by Django 5.1.3 on 2024-11-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
