# Generated by Django 5.1.3 on 2024-12-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_routes_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='driver_id',
        ),
        migrations.AlterField(
            model_name='routes',
            name='product_id',
            field=models.CharField(max_length=20),
        ),
    ]
