# Generated by Django 5.1.3 on 2024-12-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_remove_routes_driver_id_alter_routes_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='product_id',
            field=models.CharField(max_length=200),
        ),
    ]
