# Generated by Django 5.1.3 on 2024-12-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='buyer_id',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
