# Generated by Django 5.1.3 on 2024-12-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_shipment_buyer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('SC', 'sc'), ('DA', 'da'), ('SS', 'ss'), ('OP', 'op'), ('DR', 'dr'), ('SV', 'sv'), ('PC', 'pc'), ('OB', 'ob'), ('BC', 'bc')], default='unset', max_length=20),
        ),
    ]
