# Generated by Django 5.1.3 on 2024-11-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='ESP32', max_length=200),
            preserve_default=False,
        ),
    ]
