# Generated by Django 5.1.3 on 2024-12-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='maintain_humidity',
        ),
        migrations.RemoveField(
            model_name='device',
            name='maintain_temperature',
        ),
        migrations.AddField(
            model_name='device',
            name='co2_level',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='ethylene_level',
            field=models.CharField(default=5, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='remaining_distance',
            field=models.CharField(default=500, max_length=200),
            preserve_default=False,
        ),
    ]
