# Generated by Django 5.1.3 on 2024-12-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_remove_device_maintain_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='quality',
            field=models.IntegerField(default=10),
        ),
    ]
