# Generated by Django 5.1.3 on 2024-12-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_device_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='quantity',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
