# Generated by Django 5.1.3 on 2024-12-08 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_device_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='quantity',
        ),
    ]
