# Generated by Django 5.1.3 on 2024-12-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_remove_device_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='product_id',
        ),
    ]
