# Generated by Django 5.1.3 on 2024-11-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='driver_id',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
