# Generated by Django 5.1.3 on 2024-12-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
