# Generated by Django 5.1.3 on 2024-12-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='driver_approval',
            field=models.BooleanField(default=False),
        ),
    ]
