# Generated by Django 5.1.3 on 2024-12-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_driver_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='driver_approval',
        ),
    ]
