# Generated by Django 5.1.3 on 2024-12-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_driver_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_id',
        ),
    ]
