# Generated by Django 5.1.3 on 2024-12-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('driver', 'Driver'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
