# Generated by Django 5.1.3 on 2024-12-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.JSONField(default={'lat': '0.0', 'lon': '0.0'}),
            preserve_default=False,
        ),
    ]
