# Generated by Django 5.1.3 on 2024-12-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.JSONField(default={'lat': '0', 'lon': '0'}),
        ),
    ]
