# Generated by Django 5.1.3 on 2024-12-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='route_id',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
