# Generated by Django 5.1.3 on 2024-12-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_alter_driver_route_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(default='0099009900', max_length=200),
            preserve_default=False,
        ),
    ]
