# Generated by Django 5.1.3 on 2024-12-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_driver_name_driver_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='phone',
        ),
    ]
