# Generated by Django 5.1.3 on 2024-12-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_remove_driver_name_remove_driver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(default='1234567890', max_length=200),
        ),
    ]
