# Generated by Django 5.1.3 on 2024-12-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='shipment_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
