# Generated by Django 5.1.3 on 2024-12-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_bid_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='status',
        ),
    ]
